//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_it_DIY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APD65_63011212052Entities : DbContext
    {
        public APD65_63011212052Entities()
            : base("name=APD65_63011212052Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Scustomer> Scustomers { get; set; }
        public virtual DbSet<Semployee> Semployees { get; set; }
        public virtual DbSet<SOrder> SOrders { get; set; }
        public virtual DbSet<SOrderItem> SOrderItems { get; set; }
        public virtual DbSet<Sproduct> Sproducts { get; set; }
        public virtual DbSet<Spromotion> Spromotions { get; set; }
        public virtual DbSet<Sstatu> Sstatus { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
    }
}
