//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_it_DIY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semployee()
        {
            this.SOrders = new HashSet<SOrder>();
        }
    
        public int Em_ID { get; set; }
        public string Em_firstname { get; set; }
        public string Em_lastname { get; set; }
        public string Em_phone { get; set; }
        public byte[] Em_image { get; set; }
        public string Em_email { get; set; }
        public int Em_status { get; set; }
        public string Em_pssword { get; set; }
        public string Em_username { get; set; }
    
        public virtual Sstatu Sstatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrder> SOrders { get; set; }
    }
}
