//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_it_DIY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spromotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spromotion()
        {
            this.SOrders = new HashSet<SOrder>();
        }
    
        public int Pm_ID { get; set; }
        public string Pm_Pfirst { get; set; }
        public string Pm_Psecond { get; set; }
        public decimal Pm_rebate { get; set; }
        public string Pm_PfirstID { get; set; }
        public string Pm_PsecondID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrder> SOrders { get; set; }
    }
}
